# Generated by Django 3.2.13 on 2022-10-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0003_alter_review_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='grade',
            field=models.FloatField(),
        ),
    ]
